# Generated by Django 3.2.16 on 2023-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_published_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['object_id', 'created_at'], name='blog_commen_object__8e1d50_idx'),
        ),
    ]
